config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :availabilities, only: %i[ index ]
  resources :reservations, only: %i[ index destroy ]
  get '/reservations/:availability', to: 'reservations#create', as: 'new_reservations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :room
  belongs_to :hourly
end

app/models/hourly.rb
class Hourly < ApplicationRecord
    has_many :availabilities, dependent: :destroy
    has_many :reservations, dependent: :destroy
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  belongs_to :hourly
  belongs_to :teacher
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :availabilities, dependent: :destroy
    has_many :reservations, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :registerable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable, :recoverable

  has_one :teacher, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
    def index
        @availabilities = Availability.all
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def index
        @reservations = current_user.teacher.reservations
    end
    def create
        @availability = Availability.find(params[:availability])
        Reservation.create(teacher: current_user.teacher, hourly: @availability.hourly, room: @availability.room)
        @availability.destroy
        flash[:notice] = 'The room has been reserved'
        redirect_to availabilities_path
    end
    def destroy
        @reservation = Reservation.find(params[:id])
        Availability.create(hourly: @reservation.hourly, room: @reservation.room)
        @reservation.destroy
        flash[:notice] = 'The reservation has been cancelled'
        redirect_to reservations_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/availabilities/index.html.erb
<% content_for :head do %>
    <style>
      thead input {
          width: 100%;
          padding: 3px;
          box-sizing: border-box;
      }
  </style>
<% end %>

<h2 style="margin-top: 100px;" class="mx-5">Availabilities</h2>
<div class="p-5">
    <table id="example" class="table table-striped table-bordered" cellspacing="0">
        <thead>
            <tr>
                <th><span class="d-flex flex-column align-items-center">Days</span></th>
                <th><span class="d-flex flex-column align-items-center">Hourlies</span></th>
                <th><span class="d-flex flex-column align-items-center">Classrooms</span></th>
                <th><span class="d-flex flex-column align-items-center">Locations</span></th>
                <th style="text-align:center;min-width: 100px;">Actions</th>
            </tr>
        </thead>
        <tbody>
        <% @availabilities.each do |availability| %>
            <tr>
                <td><%= availability.hourly.day %></td>
                <td><%= availability.hourly.time_slot %></td>
                <td><%= availability.room.name %></td>
                <td><%= availability.room.location %></td>
                <td>

                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/home/index.html.erb
<div class="page-header section-dark" style="background-image: url('http://demos.creative-tim.com/paper-kit-2/assets/img/antoine-barres.jpg')">
    <div class="filter"></div>
    <div class="content-center">
        <div class="container">
            <div class="title-brand">
                <h1 class="presentation-title">CLASSROOMS MANAGER</h1>
                <div class="fog-low">
                    <img src="http://demos.creative-tim.com/paper-kit-2/assets/img/fog-low.png" alt="">
                </div>
                <div class="fog-low right">
                    <img src="http://demos.creative-tim.com/paper-kit-2/assets/img/fog-low.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <div class="moving-clouds" style="background-image: url('http://demos.creative-tim.com/paper-kit-2/assets/img/clouds.png'); ">

    </div>
</div>


<script>
    var searchVisible = 0;
    var transparent = true;

    var transparentDemo = true;
    var fixedTop = false;

    var navbar_initialized = false;

    $(document).ready(function(){
        window_width = $(window).width();

        //  Activate the tooltips
        $('[data-toggle="tooltip"]').tooltip();

        //      Activate the switches with icons
        if($('.switch').length != 0){
            $('.switch')['bootstrapSwitch']();
        }
        //      Activate regular switches
        if($("[data-toggle='switch']").length != 0){
            $("[data-toggle='switch']").bootstrapSwitch();
        }

        if($(".tagsinput").length != 0){
            $(".tagsinput").tagsInput();
        }
        if (window_width >= 768) {
            big_image = $('.page-header[data-parallax="true"]');

            if(big_image.length != 0){
            $(window).on('scroll', pk.checkScrollForPresentationPage);
            }
        }

        if($("#datetimepicker").length != 0){
            $('#datetimepicker').datetimepicker({
                icons: {
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-chevron-up",
                    down: "fa fa-chevron-down",
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right',
                    today: 'fa fa-screenshot',
                    clear: 'fa fa-trash',
                    close: 'fa fa-remove'
                },
                debug: true
            });
        };

        // Navbar color change on scroll
        if($('.navbar[color-on-scroll]').length != 0){
            $(window).on('scroll', pk.checkScrollForTransparentNavbar)
        }


        $('.btn-tooltip').tooltip();
        $('.label-tooltip').tooltip();

        // Carousel
        $('.carousel').carousel({
        interval: 4000
        });

        $('.form-control').on("focus", function(){
            $(this).parent('.input-group').addClass("input-group-focus");
        }).on("blur", function(){
            $(this).parent(".input-group").removeClass("input-group-focus");
        });

        // Init popovers
        pk.initPopovers();

        // Init Collapse Areas
        pk.initCollapseArea();

        // Init Sliders
        pk.initSliders();

    });


    $(document).on('click', '.navbar-toggler', function(){
        $toggle = $(this);
        if(pk.misc.navbar_menu_visible == 1) {
            $('html').removeClass('nav-open');
            pk.misc.navbar_menu_visible = 0;
            setTimeout(function(){
                $toggle.removeClass('toggled');
                $('#bodyClick').remove();
            }, 550);
        } else {
            setTimeout(function(){
                $toggle.addClass('toggled');
            }, 580);

            div = '<div id="bodyClick"></div>';
            $(div).appendTo("body").click(function() {
                $('html').removeClass('nav-open');
                pk.misc.navbar_menu_visible = 0;
                $('#bodyClick').remove();
                setTimeout(function(){
                    $toggle.removeClass('toggled');
                }, 550);
            });

            $('html').addClass('nav-open');
            pk.misc.navbar_menu_visible = 1;
        }
    });

    pk = {
        misc:{
            navbar_menu_visible: 0
        },

        checkScrollForPresentationPage: debounce(function(){
            oVal = ($(window).scrollTop() / 3);
            big_image.css({
                'transform':'translate3d(0,' + oVal +'px,0)',
                '-webkit-transform':'translate3d(0,' + oVal +'px,0)',
                '-ms-transform':'translate3d(0,' + oVal +'px,0)',
                '-o-transform':'translate3d(0,' + oVal +'px,0)'
            });
        }, 4),

        checkScrollForTransparentNavbar: debounce(function() {
                if($(document).scrollTop() > $(".navbar").attr("color-on-scroll") ) {
                    if(transparent) {
                        transparent = false;
                        $('.navbar[color-on-scroll]').removeClass('navbar-transparent');
                    }
                } else {
                    if( !transparent ) {
                        transparent = true;
                        $('.navbar[color-on-scroll]').addClass('navbar-transparent');
                    }
                }
        }, 17),

        initPopovers: function(){
            if($('[data-toggle="popover"]').length != 0){
                $('body').append('<div class="popover-filter"></div>');

                //    Activate Popovers
            $('[data-toggle="popover"]').popover().on('show.bs.popover', function () {
                    $('.popover-filter').click(function(){
                        $(this).removeClass('in');
                        $('[data-toggle="popover"]').popover('hide');
                    });
                    $('.popover-filter').addClass('in');
                }).on('hide.bs.popover', function(){
                    $('.popover-filter').removeClass('in');
                });

            }
        },
        initCollapseArea: function(){
            $('[data-toggle="pk-collapse"]').each(function () {
                var thisdiv = $(this).attr("data-target");
                $(thisdiv).addClass("pk-collapse");
            });

            $('[data-toggle="pk-collapse"]').hover(function(){
                var thisdiv = $(this).attr("data-target");
                if(!$(this).hasClass('state-open')){
                    $(this).addClass('state-hover');
                    $(thisdiv).css({
                        'height':'30px'
                    });
                }

            },
            function(){
                var thisdiv = $(this).attr("data-target");
                $(this).removeClass('state-hover');

                if(!$(this).hasClass('state-open')){
                    $(thisdiv).css({
                        'height':'0px'
                    });
                }
            }).click(function(event){
                    event.preventDefault();

                    var thisdiv = $(this).attr("data-target");
                    var height = $(thisdiv).children('.panel-body').height();

                    if($(this).hasClass('state-open')){
                        $(thisdiv).css({
                            'height':'0px',
                        });
                        $(this).removeClass('state-open');
                    } else {
                        $(thisdiv).css({
                            'height':height + 30,
                        });
                        $(this).addClass('state-open');
                    }
                });
        },
        initSliders: function(){
            // Sliders for demo purpose in refine cards section
            if($('#sliderRegular').length != 0 ){
                var rangeSlider = document.getElementById('sliderRegular');
                noUiSlider.create(rangeSlider, {
                    start: [ 5000 ],
                    range: {
                        'min': [  2000 ],
                        'max': [ 10000 ]
                    }
                });
            }
            if($('#sliderDouble').length != 0){
                var slider = document.getElementById('sliderDouble');
                noUiSlider.create(slider, {
                    start: [20, 80],
                    connect: true,
                    range: {
                        'min': 0,
                        'max': 100
                    }
                });
            }

        },


    }

    examples = {
        initContactUsMap: function(){
            var myLatlng = new google.maps.LatLng(44.433530, 26.093928);
            var mapOptions = {
            zoom: 14,
            center: myLatlng,
            scrollwheel: false, //we disable de scroll over the map, it is a really annoing when you scroll through page
            }
            var map = new google.maps.Map(document.getElementById("contactUsMap"), mapOptions);

            var marker = new google.maps.Marker({
                position: myLatlng,
                title:"Hello World!"
            });

            // To add the marker to the map, call setMap();
            marker.setMap(map);
            }
    }

    // Returns a function, that, as long as it continues to be invoked, will not
    // be triggered. The function will be called after it stops being called for
    // N milliseconds. If `immediate` is passed, trigger the function on the
    // leading edge, instead of the trailing.

    function debounce(func, wait, immediate) {
        var timeout;
        return function() {
            var context = this, args = arguments;
            clearTimeout(timeout);
            timeout = setTimeout(function() {
                timeout = null;
                if (!immediate) func.apply(context, args);
            }, wait);
            if (immediate && !timeout) func.apply(context, args);
        };
    };

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtelierGenieLogicielTp1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= yield :head %>
  <body>
    
    <div id="main">
      <div class="container_menu">
        <nav>
          <div class="nav-fostrap d-flex justify-content-center">
            <ul class="px-md-5">
              <li><%= link_to "Home", root_path %></li>
              <% if current_user %>
                <li><%= link_to "Availabilities", availabilities_path %></li>
                <li><%= link_to "My reservations", reservations_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log in", new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
          <div class="nav-bg-fostrap">
            <div class="navbar-fostrap"><span></span> <span></span> <span></span></div>
          </div>
        </nav>
      </div>
    </div>
    <% if notice %>
      <script>swal("SUCCESS", "<%= notice %>".split("&#39;").join("'"),"success")</script>
    <% end %>
    <% if alert %>
      <script>swal("WARNING", "<%= alert %>".split("&#39;").join("'"), "warning")</script>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<% content_for :head do %>
    <style>
      thead input {
          width: 100%;
          padding: 3px;
          box-sizing: border-box;
      }
  </style>
<% end %>

<h2 style="margin-top: 100px;" class="mx-5">Reservations</h2>
<div class="p-lg-5">
    <table id="example" class="table table-striped table-bordered text-center" cellspacing="0">
        <thead>
            <tr>
                <th><span class="d-flex flex-column align-items-center">Classrooms</span></th>
                <th><span class="d-flex flex-column align-items-center">Locations</span></th>
                <th><span class="d-flex flex-column align-items-center">Days</span></th>
                <th><span class="d-flex flex-column align-items-center">Hourlies</span></th>
                <th style="text-align:center;min-width: 100px;">Actions</th>
            </tr>
        </thead>
        <tbody>
        <% @reservations.each do |reservation| %>
            <tr>
                <td><%= reservation.room.name %></td>
                <td><%= reservation.room.location %></td>
                <td><%= reservation.hourly.day %></td>
                <td><%= reservation.hourly.time_slot %></td>
                <td>
                    <%= link_to "Cancel", new_reservations_path(reservation), method: :delete, class: "btn btn-danger" %>
                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>